### ISSUE TITLE
Gather Use Case Insights from Credera Colleagues

### ISSUE THREAD

**Issue by gfcredera** [crederauk/infra-guard-aws#9]
**Description:**
To enhance Infra Guard's capabilities, we need to gather insights from Credera colleagues regarding potential use cases that could benefit their projects. This will help identify new scenarios and requirements for AWS infrastructure test automation that the tool should support. We will achieve this by conducting a survey, such as a Google Forms questionnaire, and sharing it via internal communication channels (e.g., Slack or email). The collected responses will inform future feature development and backlog prioritisation.

**Acceptance Criteria:**
1. A questionnaire is created (Google Forms or similar) to gather feedback on potential use cases for Infra Guard.
2. The survey is shared in relevant internal Credera channels.
3. Responses are collected and analysed.
4. A summary report of the key insights is created and linked in this issue.
5. New potential use cases are identified based on the survey results.
6. New GitHub issues are created for these use cases.

**Comment by vidyakdl** [comment]
I will again send this off in New year once cloud capability kicks off.
